version: '3'
services:
  app:
    image: dyoshikawa/ridgepole:latest
    working_dir: /work
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: secret
    command: sh
    tty: true
    volumes:
      - .:/work
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
